### PR TITLE
A17 Update

### PR DESCRIPTION
**Pull request by ProximityMicrowave**
Updated the code to fit with the API changes in A17.

### CODE REVIEW

**Comment by jakevose** [comment]
Hey! Thanks for doing this. I'll take a look at the PR tonight.

**Comment by ProximityMicrowave** [comment]
Sure. Sorry the submission is a bit of a mess, I've never done a Pull Request to someone else's code and I messed up somewhere trying to figure it all out. I only changed a few lines even though it thinks I changed every line of code.

**Comment by jakevose** [comment]
I think it's just line endings. :-)

**Comment by jakevose** [comment]
Ok so -- this works great, but I guess I don't understand the respawningAfterLoad value. Is there a reason you hardcoded true vs. passing it?

**Pull request merged**
